### ISSUE TITLE
Creating a new instance of yt-dlp at channel join

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [jontze/cadency-rs#74]
**Is your feature request related to a problem? Please describe.**
Currently, there is quite a delay between sending a play command and the bot actually playing the song.

**Describe the solution you'd like**
I think the main issue is that a new yt-dlp instance is created for each time the play command is executed (add_song method in voice.rs). The documentation of songbird mentions a high cost of creating a new instance, which I think has something to do with the relatively long loading times. I think a possible solution would be creating a new instance when the bot joins a channel (the join method in voice.rs) and cache the resuling instance with a package [like this](https://crates.io/crates/simple-cache). I would implement it myself if I knew how 😅.

**Comment by jontze** [comment]
Thanks for the issue! I'm currently investigating this. 

From what I got so far from going through the docs and source code of songbird is, that the costs for _"restarting and seeking_ [on a track] _will probably be very high: expect a pause if you seek backwards"_ [¹](https://serenity-rs.github.io/songbird/current/songbird/input/restartable/struct.Restartable.html#method.ytdl). By calling the `ytdl` function from songbird we basically just call the `yt-dlp` executable which will return the song in a certain format or at least metadata of the song. So I don't think that we could cache something here (correct me if I got you wrong).

However, currently we are adding every song lazy to the queue. This is at least for the first song not optimal. Because lazy means, from what I understood, that we are fetching the metadata first and start to serve the song only as needed. This doesn't make sense for the first song in the queue as we need this one immediately ([²](https://serenity-rs.github.io/songbird/current/songbird/input/restartable/struct.Restartable.html#method.new) and [³](https://github.com/serenity-rs/songbird/blob/current/src/input/restartable.rs#L164-L167)).

So one change I will try out here is to only add tracks lazy to the queue if they are not the first. This should in theory improve the performance here. But be aware that this is probably only a drop in the ocean as the most important aspects here are e.g. the network connection (yt-dlp download), yt-dlp execution (python) and correct encoding to a format that discord can understand (there is already some work on improving the encoding https://github.com/serenity-rs/songbird/issues/123 ).

**Comment by jontze** [comment]
@TeaDrinkingProgrammer I pushed a change to the development branch. This should reduce the time until the fist track starts playing slightly.

**Comment by TeaDrinkingProgrammer** [comment]
> @TeaDrinkingProgrammer I pushed a change to the development branch. This should reduce the time until the fist track starts playing slightly.

I just tried cold-booting both Jmusicbot (my current go-to musicbot) and cadencyrs and they were quite similar, even without the new optimisation :). Only thing that was a bit slower in Cadencyrs is the processing of commands like skip or play when the bot is already up, but I understand now that this is also because Songbird is also still under heavy development. I am interested to see where this goes and I hope I can ditch Jmusicbot soon :).

**Comment by jontze** [comment]
Thanks for your feedback! :) 
I will continue looking into more performance optimizations for the audio commands as there is definitely room for improvement. However, I'll add the `help-wanted` tag to the issue as I'm open to suggestions how we can achieve this.

**Comment by jontze** [comment]
With the move to serenity `0.12.x` and songbird `0.4.x` the behavior changed quite a bit. Now every time a song is added to the from serenity managed queue we just save the metadata to the queue. The song is then fetched, encoded and played lazy only when actually needed. Therefore, I'm gonna close this issue.

The rest stays the same. Serenity/Songbird still just call yt-dlp under the hood.

Close with #133
